global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik_traefik
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik
    watch: true
